package Domain;

public enum  State {
     WAITING, SERVERSTART, CLIENTSTARTSGAME, SERVERSENTWHATCATEGORYQUESTION, CLIENTPICKEDSUBJECT, SERVERCONFIGUREDROND, SERVERSENTQUESTION, CLIENTCLICKEDANSWER, SERVERSENTANSWER, ANOTHERQUESTION, RESULTSCREEN, FINISHEDGAME;
}
