package Domain;

public enum  State {
     WAITING, SERVERSENTWHATCATEGORYQUESTION, CLIENTPICKEDSUBJECT, SERVERCONFIGUREDROND, SERVERSENTQUESTION, CLIENTCLICKEDANSWER, SERVERSENTANSWER, ANOTHERQUESTION;
}