package Domain;

<<<<<<< HEAD
public enum  State {
     WAITING, SERVERSTART, CLIENTSTARTSGAME, SERVERSENTWHATCATEGORYQUESTION, CLIENTPICKEDSUBJECT, SERVERCONFIGUREDROND, SERVERSENTQUESTION, CLIENTCLICKEDANSWER, SERVERSENTANSWER, ANOTHERQUESTION, RESULTSCREEN, FINISHEDGAME;
=======
public enum State {
    LOADGAME, FIRST, MIDDLE, FINAL, GAMECOMPLETE;
>>>>>>> master
}
